<?php
/**
 * @file
 * Code for the Splash Image feature.
 */

include_once('splash_image.features.inc');

/**
 * Implements hook_form_NODE_ID_alter().
 */
function splash_image_form_splash_node_form_alter(&$form, &$form_state, $form_id) {
  // Remove lables for Title and Body fields
  $form['field_splashimage']['und'][0]['#title_display'] = 'none';
  // Remove vertical tabs and text-format display
  $form['#after_build'][] = '_splash_image_form_after_build';
  // Remove Delete button
  $form['actions']['delete']['#access'] = FALSE;  
}

/**
 * After-build handler for node-edit form.
 */
function _splash_image_form_after_build($form) {
  // Remove vertical tabs from the form
  $form['revision_information']['#access'] = FALSE;
  $form['author']['#access'] = FALSE;
  $form['options']['#access'] = FALSE;
  $form['path']['#access'] = FALSE;
  return $form;
}